# Generated by Django 5.2.17 on 2026-09-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('tier', models.PositiveSmallIntegerField(help_text='1 for top division, 2 for second division, etc.')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True)),
                ('stadium_name', models.CharField(blank=True, max_length=150, null=True)),
                ('crest_url', models.URLField(blank=True, null=True)),
                ('leagues', models.ManyToManyField(related_name='clubs', to='clubs.league')),
            ],
        ),
    ]
