# Generated by Django 5.2.17 on 2026-09-12 02:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('birth_date', models.DateField()),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('preferred_foot', models.CharField(choices=[('R', 'Right'), ('L', 'Left'), ('B', 'Both')], max_length=1)),
                ('position', models.CharField(choices=[('GK', 'Goalkeeper'), ('CB', 'Center Back'), ('LB', 'Left Back'), ('RB', 'Right Back'), ('DM', 'Defensive Midfielder'), ('CM', 'Central Midfielder'), ('AM', 'Attacking Midfielder'), ('LW', 'Left Winger'), ('RW', 'Right Winger'), ('ST', 'Striker')], max_length=2)),
                ('current_club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='players', to='clubs.club')),
            ],
        ),
    ]
