# Generated by Django 5.2.17 on 2026-09-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveSmallIntegerField(default=0)),
                ('assists', models.PositiveSmallIntegerField(default=0)),
                ('matches_played', models.PositiveSmallIntegerField(default=0)),
                ('minutes_played', models.PositiveSmallIntegerField(default=0)),
                ('yellow_cards', models.PositiveSmallIntegerField(default=0)),
                ('red_cards', models.PositiveSmallIntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='players.season')),
            ],
        ),
    ]
